# Generated by Django 5.2 on 2025-07-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_alter_agendamento_motivo_cancelamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
